import type {Metadata} from 'next'
import localFont from 'next/font/local'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'
import {ReactNode} from 'react'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const RootLayout = ({children}: Readonly<{ children: ReactNode }>) => (
	<html lang="en">
		<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-950`}>
			{/* PROGRESS BAR */}
			<NextTopLoader showSpinner={false} color="#facc15" />
			<div className="[&>main]:min-h-svh w-full mx-auto max-w-[600px] px-6 [&>main]:py-6">
				{children}
			</div>
		</body>
	</html>
)
export default RootLayout
